console.log("web-app ------------");

// import "./LazyMan";
// import "./New";
// import "./curry-add";
// import "./instanceof";
// import "./bind";
// import "./call-apply";
// import "./event";
// import "./clone-deep";
// import "./dom-traverse";
// import "./convert-to-tree"
// import "./convert-to-array"
// import "./LRU"
// import "./prototype"
// import "./instance"
// import "./闭包"
// import './合并两个递增数组'
// import "./this"
import "./机器人走方格";
// import "./lego";
// import "./数组第二大";
// import "./进制转换";
// import "./js输出1";
// import "./x的平方根";
// import "./dom-深度优先遍历";
// import "./dom-广度优先遍历";
// import "./扁平化数组";
// import "./手写new";
// import "./手写bind";
// import "./手写call";
// import "./原型链";
// import "./深拷贝";
// import "./数组转树";
// import "./树转数组";
// import "./对象赋值";
// import "./原型";
// import "./函数参数";
// import "./防抖节流";
// import "./箭头函数";
// import "./for-in和for-of";
